# Generated by Django 4.0.3 on 2022-05-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='NAN', max_length=255),
            preserve_default=False,
        ),
    ]
