# Generated by Django 4.0.3 on 2022-05-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_review_customer_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(default='-', max_length=255),
            preserve_default=False,
        ),
    ]
