# Generated by Django 4.0.3 on 2022-05-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cancel_order', 'Can cancel an order')]},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['birth_date'], name='store_custo_birth_d_2862da_idx'),
        ),
    ]
